name: End-to-end tests
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install a project and cypress with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      - name: Run Cypress tests
#        run: npm run test:chrome
        run: npm run -s cypress:run -- -e username=$TESTUSERNAME,password=$TESTPASSWORD
        continue-on-error: true
