# name: End-to-end tests
# on: [push]
# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Cypress run
#         uses: cypress-io/github-action@v1
#         with:
#           build: npm run build
#           start: npm test
#           wait-on: http://localhost:3030


# This is a basic workflow to help you get started with Actions

name: End-to-end tests
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        run: npm test

#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
#          start: npm test
